# Generated by Django 4.2.3 on 2025-12-29 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklySpiritualDiscipline",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                ("practice", models.CharField(max_length=500, verbose_name="내용")),
                ("week_start_sunday", models.DateField(help_text="해당 주의 일요일 날짜", verbose_name="주 시작일 (일요일)")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="유저"
                    ),
                ),
            ],
            options={
                "verbose_name": "(주간) 경건의 훈련",
                "verbose_name_plural": "(주간) 경건의 습관",
                "db_table": "weekly_spiritual_discipline",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SpiritualDiscipline",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                (
                    "timezone_offset",
                    models.IntegerField(blank=True, help_text="디바이스와 UTC간의 차이", null=True, verbose_name="분단위"),
                ),
                ("local_date", models.DateField(db_index=True, verbose_name="사용자 타임존 기준, 실제 날짜")),
                (
                    "recognized_date",
                    models.DateField(db_index=True, help_text="04:00 기준, 인정되는 날짜", verbose_name="통계에서 사용되는 날짜"),
                ),
                (
                    "weekly_sd",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="spiritual_discipline.weeklyspiritualdiscipline",
                        verbose_name="한 주의 내용 (경건의 훈련)",
                    ),
                ),
            ],
            options={
                "verbose_name": "(데일리) 경건의 훈련",
                "verbose_name_plural": "(데일리) 경건의 습관",
                "db_table": "spiritual_discipline",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="weeklyspiritualdiscipline",
            constraint=models.UniqueConstraint(
                fields=("user", "week_start_sunday"), name="unique_user_spiritual_discipline"
            ),
        ),
        migrations.AddConstraint(
            model_name="spiritualdiscipline",
            constraint=models.UniqueConstraint(
                fields=("weekly_sd", "recognized_date"), name="unique_weekly_sd_recognized_date"
            ),
        ),
    ]
