# Generated by Django 4.2.3 on 2025-12-29 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sermon",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                (
                    "worship_type",
                    models.CharField(
                        choices=[("sunday", "주일"), ("overnight", "철야")],
                        default="sunday",
                        max_length=10,
                        verbose_name="예배 종류",
                    ),
                ),
                ("youtube_link", models.URLField(verbose_name="유튜브 링크")),
                ("title", models.CharField(max_length=128, verbose_name="제목")),
                ("content", models.TextField(verbose_name="내용")),
                ("preached_date", models.DateField(verbose_name="설교일자")),
                (
                    "overnight_worship_type",
                    models.CharField(
                        blank=True,
                        choices=[("friday_night", "금요집회"), ("thursday_night", "목요집회")],
                        max_length=40,
                        null=True,
                        verbose_name="철야예배 종류",
                    ),
                ),
            ],
            options={
                "verbose_name": "설교",
                "verbose_name_plural": "설교",
                "db_table": "sermon",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SundayPreacher",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(help_text="이름, 직책 포함해서 입력해 주세요.", max_length=100, unique=True, verbose_name="설교자"),
                ),
            ],
            options={
                "verbose_name": "0. 주일예배 설교자",
                "verbose_name_plural": "0. 주일예배 설교자",
                "db_table": "sunday_preacher",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="SermonWatch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                (
                    "sermon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sermon.sermon", verbose_name="설교"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="사용자"
                    ),
                ),
            ],
            options={
                "verbose_name": "설교 시청 여부",
                "verbose_name_plural": "설교 시청 여부",
                "db_table": "sermon_watch",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SermonBookmark",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                (
                    "sermon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sermon.sermon", verbose_name="설교"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="사용자"
                    ),
                ),
            ],
            options={
                "verbose_name": "설교 북마크",
                "verbose_name_plural": "설교 북마크",
                "db_table": "sermon_bookmark",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="sermon",
            name="sunday_preacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sermon.sundaypreacher",
                verbose_name="주일예배 설교자",
            ),
        ),
        migrations.CreateModel(
            name="OvernightSermon",
            fields=[],
            options={
                "verbose_name": "2. 철야예배 설교",
                "verbose_name_plural": "2. 철야예배 설교",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("sermon.sermon",),
        ),
        migrations.CreateModel(
            name="SundaySermon",
            fields=[],
            options={
                "verbose_name": "1. 주일예배 설교",
                "verbose_name_plural": "1. 주일예배 설교",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("sermon.sermon",),
        ),
        migrations.AddConstraint(
            model_name="sermonwatch",
            constraint=models.UniqueConstraint(fields=("user", "sermon"), name="unique_user_sermon_watch"),
        ),
        migrations.AddConstraint(
            model_name="sermonbookmark",
            constraint=models.UniqueConstraint(fields=("user", "sermon"), name="unique_user_sermon_bookmark"),
        ),
    ]
