# Generated by Django 4.2.3 on 2025-12-29 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                ("user_name", models.CharField(blank=True, max_length=50, null=True, verbose_name="작성자 이름")),
                ("user_phone", models.CharField(blank=True, max_length=11, null=True, verbose_name="작성자 휴대폰")),
                ("user_church_name", models.CharField(blank=True, max_length=100, null=True, verbose_name="작성자 출석교회")),
                ("title", models.CharField(max_length=128, verbose_name="제목")),
                ("content", models.TextField(verbose_name="내용")),
                (
                    "user",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "문의하기",
                "verbose_name_plural": "문의하기",
                "db_table": "inquiry",
                "ordering": ["-created_at"],
            },
        ),
    ]
