# Generated by Django 4.2.3 on 2025-12-29 05:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("privacy_policy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TermsOfService",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                ("version", models.IntegerField(editable=False)),
                ("content", ckeditor.fields.RichTextField(verbose_name="내용")),
            ],
            options={
                "verbose_name": "이용약관",
                "verbose_name_plural": "1. 서비스 이용약관",
                "db_table": "terms_of_service",
                "ordering": ["-version"],
            },
        ),
        migrations.CreateModel(
            name="PrivacyPolicyProxy",
            fields=[],
            options={
                "verbose_name": "2. 개인정보 처리방침",
                "verbose_name_plural": "2. 개인정보 처리방침",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("privacy_policy.privacypolicy",),
        ),
    ]
