# Generated by Django 4.2.3 on 2025-12-29 05:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PrivacyPolicy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                ("version", models.IntegerField(editable=False)),
                ("content", ckeditor.fields.RichTextField(verbose_name="내용")),
            ],
            options={
                "verbose_name": "개인정보처리방침",
                "verbose_name_plural": "개인정보처리방침",
                "db_table": "privacy_policy",
                "ordering": ["-version"],
            },
        ),
    ]
