# Generated by Django 4.2.3 on 2026-07-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HomeContent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                (
                    "eyebrow",
                    models.CharField(default="하나님과 더 가까워지는 거룩한 습관", max_length=80, verbose_name="상단 꼬리표"),
                ),
                ("main_title", models.CharField(max_length=120, verbose_name="메인 제목")),
                ("sub_title", models.TextField(verbose_name="서브 설명")),
                ("highlight_text", models.CharField(blank=True, default="", max_length=120, verbose_name="강조 문구")),
                ("cta_text", models.CharField(blank=True, default="", max_length=80, verbose_name="CTA 문구")),
                ("cta_link", models.URLField(blank=True, default="", verbose_name="CTA 링크")),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화 여부")),
            ],
            options={
                "verbose_name": "홈 콘텐츠",
                "verbose_name_plural": "홈 콘텐츠",
                "db_table": "home_content",
                "ordering": ["-is_active", "-updated_at", "-created_at"],
            },
        ),
    ]
