# Generated by Django 4.2.3 on 2025-12-29 05:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyMortificationOfSin",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                (
                    "slot",
                    models.CharField(
                        choices=[("first", "죄와의 싸움 1"), ("second", "죄와의 싸움 2")], max_length=10, verbose_name="순서"
                    ),
                ),
                ("practice", models.CharField(max_length=500, verbose_name="내용")),
                ("week_start_sunday", models.DateField(help_text="해당 주의 일요일 날짜", verbose_name="주 시작일 (일요일)")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="유저"
                    ),
                ),
            ],
            options={
                "verbose_name": "(주간) 죄 죽이기",
                "verbose_name_plural": "(주간) 죄와의 싸움",
                "db_table": "weekly_mortification_of_sin",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MortificationOfSin",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="0~10점 사이의 점수",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="점수",
                    ),
                ),
                (
                    "timezone_offset",
                    models.IntegerField(blank=True, help_text="디바이스와 UTC간의 차이", null=True, verbose_name="분단위"),
                ),
                ("local_date", models.DateField(db_index=True, verbose_name="사용자 타임존 기준, 실제 날짜")),
                (
                    "recognized_date",
                    models.DateField(db_index=True, help_text="04:00 기준, 인정되는 날짜", verbose_name="통계에서 사용되는 날짜"),
                ),
                (
                    "weekly_mos",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_mos_set",
                        to="mortification_of_sin.weeklymortificationofsin",
                        verbose_name="한 주의 내용 (죄와의 싸움)",
                    ),
                ),
            ],
            options={
                "verbose_name": "(데일리) 죄 죽이기",
                "verbose_name_plural": "(데일리) 죄와의 싸움",
                "db_table": "mortification_of_sin",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="weeklymortificationofsin",
            constraint=models.UniqueConstraint(
                fields=("user", "slot", "week_start_sunday"), name="unique_user_slot_week_mortification_of_sin"
            ),
        ),
    ]
