# Generated by Django 4.2.3 on 2025-12-29 05:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("withdrawal_user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="withdrawaluser",
            options={"ordering": ["-deleted_at"], "verbose_name": "탈퇴한 유저", "verbose_name_plural": "탈퇴한 유저"},
        ),
        migrations.AlterModelManagers(
            name="withdrawaluser",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="withdrawaluser",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="withdrawaluser",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="withdrawaluser",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="withdrawaluser",
            name="username",
        ),
        migrations.AddField(
            model_name="withdrawaluser",
            name="birth_date",
            field=models.CharField(
                default=19910101,
                help_text="YYYYMMDD 형식",
                max_length=8,
                validators=[django.core.validators.validate_integer, django.core.validators.MinLengthValidator(8)],
                verbose_name="생년월일",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="withdrawaluser",
            name="church_name",
            field=models.CharField(
                blank=True, default="", help_text="탈퇴 시점의 출석교회", max_length=100, verbose_name="출석교회"
            ),
        ),
        migrations.AddField(
            model_name="withdrawaluser",
            name="deleted_at",
            field=models.DateTimeField(default="2025-12-25", help_text="사용자가 탈퇴한 일시", verbose_name="계정 삭제 일시"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="withdrawaluser",
            name="gender",
            field=models.CharField(
                choices=[("male", "남성"), ("female", "여성")], default="male", max_length=10, verbose_name="성별"
            ),
        ),
        migrations.AddField(
            model_name="withdrawaluser",
            name="name",
            field=models.CharField(default="test_user", max_length=50, verbose_name="이름"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="withdrawaluser",
            name="user_created_at",
            field=models.DateTimeField(
                default="2025-12-25", help_text="원래 User 객체가 생성된 일시", verbose_name="사용자 계정 생성 일시"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="withdrawaluser",
            name="email",
            field=models.EmailField(help_text="탈퇴한 유저의 이메일", max_length=254, verbose_name="이메일"),
        ),
        migrations.AlterField(
            model_name="withdrawaluser",
            name="phone",
            field=models.CharField(
                blank=True,
                default="",
                help_text="탈퇴 시점의 휴대폰 번호",
                max_length=11,
                validators=[django.core.validators.validate_integer, django.core.validators.MinLengthValidator(10)],
                verbose_name="휴대폰",
            ),
        ),
    ]
