# Generated by Django 4.2.3 on 2025-12-29 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bible",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                ("data", models.FileField(upload_to="bible/", verbose_name="데이터")),
            ],
            options={
                "verbose_name": "성경",
                "verbose_name_plural": "성경",
                "db_table": "bible",
            },
        ),
    ]
