# Generated by Django 4.2.3 on 2025-12-29 05:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("withdrawal_user", "0002_alter_withdrawaluser_options_and_more"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WithdrawalUserProxy",
            fields=[],
            options={
                "verbose_name": "2. 탈퇴한 유저",
                "verbose_name_plural": "2. 탈퇴한 유저",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("withdrawal_user.withdrawaluser",),
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "유저", "verbose_name_plural": "1. 회원"},
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(blank=True, default="", max_length=200, verbose_name="주소"),
        ),
        migrations.AddField(
            model_name="user",
            name="address_detail",
            field=models.CharField(blank=True, default="", max_length=200, verbose_name="상세주소"),
        ),
        migrations.AddField(
            model_name="user",
            name="birth_date",
            field=models.CharField(
                default=19900101,
                help_text="YYYYMMDD 형식",
                max_length=8,
                validators=[django.core.validators.validate_integer, django.core.validators.MinLengthValidator(8)],
                verbose_name="생년월일",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="church_name",
            field=models.CharField(blank=True, default="", max_length=100, verbose_name="출석교회"),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("male", "남성"), ("female", "여성")], default="male", max_length=10, verbose_name="성별"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(
                default="admin",
                help_text="최초 생성(설정) 이후 변경 불가능, 변경하고 싶다면 관리자페이지에서 직접 제어",
                max_length=50,
                verbose_name="이름",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="postal_code",
            field=models.CharField(blank=True, default="", max_length=20, verbose_name="우편번호"),
        ),
        migrations.AddField(
            model_name="user",
            name="residence",
            field=models.CharField(
                blank=True,
                choices=[("domestic", "국내"), ("overseas", "국외")],
                default="",
                max_length=10,
                verbose_name="거주지",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="social_kind",
            field=models.CharField(
                blank=True,
                choices=[("kakao", "카카오"), ("apple", "애플")],
                max_length=8,
                null=True,
                verbose_name="소셜로그인 종류",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="이메일"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                default="",
                help_text="최초 생성(설정) 이후 변경 불가능, 변경하고 싶다면 관리자페이지에서 직접 제어",
                max_length=11,
                validators=[django.core.validators.validate_integer, django.core.validators.MinLengthValidator(10)],
                verbose_name="휴대폰",
            ),
        ),
        migrations.CreateModel(
            name="UserPushSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                ("is_weekly_summary_alarm_enabled", models.BooleanField(default=False, verbose_name="통계 알림 여부")),
                ("alarm_time", models.TimeField(blank=True, null=True, verbose_name="오늘의 체크 알림 시간 (UTC)")),
                (
                    "timezone_offset",
                    models.IntegerField(default=0, help_text="디바이스와 UTC간의 차이(reset할 때 해당 값만 변경)", verbose_name="분단위"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_user_settings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="유저",
                    ),
                ),
            ],
            options={
                "verbose_name": "유저별 푸시 설정",
                "verbose_name_plural": "유저별 푸시 설정",
                "db_table": "user_push_setting",
                "ordering": ["-created_at"],
            },
        ),
    ]
