# Generated by Django 4.2.3 on 2025-12-29 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyCheckStatus",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "check_type",
                    models.CharField(
                        choices=[("som_reading_status", "산상수훈"), ("worship", "예배")], max_length=20, verbose_name="체크 유형"
                    ),
                ),
                ("created_at", models.DateTimeField(help_text="UTC 기준", verbose_name="생성일시(읽은일시)")),
                (
                    "timezone_offset",
                    models.IntegerField(blank=True, help_text="디바이스와 UTC간의 차이", null=True, verbose_name="분단위"),
                ),
                ("local_date", models.DateField(db_index=True, help_text="사용자 타임존 기준, 실제 날짜")),
                ("recognized_date", models.DateField(db_index=True, help_text="04:00 기준, 인정되는 날짜")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "(예배/산상수훈) 매일 체크 상태",
                "verbose_name_plural": "(예배/산상수훈) 매일 체크 상태",
                "db_table": "daily_check_status",
                "ordering": ["-created_at"],
            },
        ),
    ]
