# Generated by Django 4.2.3 on 2025-12-29 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PrayTimeLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "type",
                    models.CharField(
                        choices=[("timer", "타이머"), ("stopwatch", "스톱워치"), ("manual", "수동입력")],
                        max_length=20,
                        verbose_name="기록 방식",
                    ),
                ),
                ("created_at", models.DateTimeField(help_text="UTC 기준", verbose_name="생성일시(읽은일시)")),
                (
                    "timezone_offset",
                    models.IntegerField(blank=True, help_text="디바이스와 UTC간의 차이", null=True, verbose_name="분단위"),
                ),
                ("local_date", models.DateField(db_index=True, verbose_name="사용자 타임존 기준, 실제 날짜")),
                (
                    "recognized_date",
                    models.DateField(db_index=True, help_text="04:00 기준, 인정되는 날짜", verbose_name="통계에서 사용되는 날짜"),
                ),
                (
                    "started_time",
                    models.TimeField(
                        blank=True,
                        help_text="스톱워치일 때는 값을 넣어줍니다. 타이머/수동일 때는 null처리",
                        null=True,
                        verbose_name="(스톱워치용)시작시간",
                    ),
                ),
                (
                    "ended_time",
                    models.TimeField(
                        blank=True,
                        help_text="스톱워치일 때는 값을 넣어줍니다. 타이머/수동일 때는 null처리",
                        null=True,
                        verbose_name="(스톱워치용)종료시간",
                    ),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(help_text="기도한 시간을 초 단위로 저장 (최대 86,400초)", verbose_name="기도 시간(초)"),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "기도 시간 기록",
                "verbose_name_plural": "기도 시간 기록",
                "db_table": "pray_time_log",
                "ordering": ["-created_at"],
            },
        ),
    ]
