# Generated by Django 4.2.3 on 2025-12-29 05:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inquiry", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                ("title", models.CharField(help_text="제목은 최대 24자입니다.", max_length=24, verbose_name="제목")),
                ("content", ckeditor.fields.RichTextField(verbose_name="내용")),
            ],
            options={
                "verbose_name": "공지사항",
                "verbose_name_plural": "1. 공지사항 등록",
                "db_table": "notification",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InquiryProxy",
            fields=[],
            options={
                "verbose_name": "2. 문의 내역 확인",
                "verbose_name_plural": "2. 문의 내역 확인",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("inquiry.inquiry",),
        ),
    ]
