# Generated by Django 4.2.3 on 2025-12-29 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("device", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PushLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                (
                    "type",
                    models.CharField(
                        choices=[("statistics_notification", "통계 알림"), ("daily_check_notification", "오늘의 체크 알림")],
                        max_length=25,
                        verbose_name="푸시 알림 종류",
                    ),
                ),
                ("title", models.CharField(max_length=128, verbose_name="제목")),
                ("content", models.TextField(verbose_name="내용")),
                (
                    "navigation_data",
                    models.JSONField(
                        blank=True, help_text="앱에서 알림 클릭 시 이동할 화면 정보 (JSON 형태)", null=True, verbose_name="네비게이션 데이터"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("R", "대기"), ("S", "성공"), ("F", "실패")], default="R", max_length=1, verbose_name="상태"
                    ),
                ),
                ("fail_reason", models.TextField(blank=True, default="", verbose_name="실패사유")),
                ("to_set", models.ManyToManyField(to="device.device", verbose_name="수신자")),
            ],
            options={
                "verbose_name": "푸시 로그",
                "verbose_name_plural": "푸시 로그",
                "db_table": "push_log",
            },
        ),
    ]
