# Generated by Django 4.2.3 on 2026-06-25 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyScreenTimeLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("minutes", models.IntegerField()),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "일별 스크린타임 기록",
                "verbose_name_plural": "일별 스크린타임 기록",
                "db_table": "daily_screen_time_log",
                "ordering": ["-date", "-id"],
                "unique_together": {("user", "date")},
            },
        ),
    ]
