# Generated by Django 4.2.3 on 2025-12-29 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BibleHighlight",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                (
                    "book",
                    models.CharField(
                        choices=[
                            ("GENESIS", "창세기"),
                            ("EXODUS", "출애굽기"),
                            ("LEVITICUS", "레위기"),
                            ("NUMBERS", "민수기"),
                            ("DEUTERONOMY", "신명기"),
                            ("JOSHUA", "여호수아"),
                            ("JUDGES", "사사기"),
                            ("RUTH", "룻기"),
                            ("1_SAMUEL", "사무엘상"),
                            ("2_SAMUEL", "사무엘하"),
                            ("1_KINGS", "열왕기상"),
                            ("2_KINGS", "열왕기하"),
                            ("1_CHRONICLES", "역대상"),
                            ("2_CHRONICLES", "역대하"),
                            ("EZRA", "에스라"),
                            ("NEHEMIAH", "느헤미야"),
                            ("ESTHER", "에스더"),
                            ("JOB", "욥기"),
                            ("PSALMS", "시편"),
                            ("PROVERBS", "잠언"),
                            ("ECCLESIASTES", "전도서"),
                            ("SONG_OF_SONGS", "아가"),
                            ("ISAIAH", "이사야"),
                            ("JEREMIAH", "예레미야"),
                            ("LAMENTATIONS", "예레미야애가"),
                            ("EZEKIEL", "에스겔"),
                            ("DANIEL", "다니엘"),
                            ("HOSEA", "호세아"),
                            ("JOEL", "요엘"),
                            ("AMOS", "아모스"),
                            ("OBADIAH", "오바댜"),
                            ("JONAH", "요나"),
                            ("MICAH", "미가"),
                            ("NAHUM", "나훔"),
                            ("HABAKKUK", "하박국"),
                            ("ZEPHANIAH", "스바냐"),
                            ("HAGGAI", "학개"),
                            ("ZECHARIAH", "스가랴"),
                            ("MALACHI", "말라기"),
                            ("MATTHEW", "마태복음"),
                            ("MARK", "마가복음"),
                            ("LUKE", "누가복음"),
                            ("JOHN", "요한복음"),
                            ("ACTS", "사도행전"),
                            ("ROMANS", "로마서"),
                            ("1_CORINTHIANS", "고린도전서"),
                            ("2_CORINTHIANS", "고린도후서"),
                            ("GALATIANS", "갈라디아서"),
                            ("EPHESIANS", "에베소서"),
                            ("PHILIPPIANS", "빌립보서"),
                            ("COLOSSIANS", "골로새서"),
                            ("1_THESSALONIANS", "데살로니가전서"),
                            ("2_THESSALONIANS", "데살로니가후서"),
                            ("1_TIMOTHY", "디모데전서"),
                            ("2_TIMOTHY", "디모데후서"),
                            ("TITUS", "디도서"),
                            ("PHILEMON", "빌레몬서"),
                            ("HEBREWS", "히브리서"),
                            ("JAMES", "야고보서"),
                            ("1_PETER", "베드로전서"),
                            ("2_PETER", "베드로후서"),
                            ("1_JOHN", "요한일서"),
                            ("2_JOHN", "요한이서"),
                            ("3_JOHN", "요한삼서"),
                            ("JUDE", "유다서"),
                            ("REVELATION", "요한계시록"),
                        ],
                        max_length=20,
                        verbose_name="성경",
                    ),
                ),
                ("chapter", models.PositiveIntegerField(verbose_name="장")),
                ("verse", models.PositiveIntegerField(verbose_name="절")),
                (
                    "color",
                    models.CharField(
                        choices=[("red", "빨강"), ("yellow", "노랑"), ("green", "초록"), ("blue", "파랑"), ("purple", "보라")],
                        max_length=20,
                        verbose_name="색상",
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "성경 하이라이트",
                "verbose_name_plural": "성경 하이라이트",
                "db_table": "bible_highlight",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="biblehighlight",
            constraint=models.UniqueConstraint(
                fields=("user", "book", "chapter", "verse", "color"), name="unique_user_bible_highlight"
            ),
        ),
    ]
