# Generated by Django 4.2.3 on 2025-12-29 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PrayerBgmTrack",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                ("order", models.PositiveIntegerField(db_index=True, editable=False, verbose_name="order")),
                ("title", models.CharField(max_length=100, verbose_name="BGM 제목")),
                ("audio_file", models.FileField(upload_to="prayer_bgm/audio/", verbose_name="음원 파일")),
                (
                    "thumbnail_image",
                    models.ImageField(blank=True, null=True, upload_to="prayer_bgm/thumbnail/", verbose_name="썸네일 이미지"),
                ),
                ("duration_seconds", models.PositiveIntegerField(help_text="진행바 표시용", verbose_name="총 재생 시간(초)")),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화 여부")),
            ],
            options={
                "verbose_name": "기도용 BGM",
                "verbose_name_plural": "기도용 BGM",
                "db_table": "prayer_bgm_track",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PrayerBgmListeningState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                ("last_position_seconds", models.PositiveIntegerField(default=0, verbose_name="마지막 재생 위치(초)")),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prayer_bgm_track.prayerbgmtrack",
                        verbose_name="기도용 BGM",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="유저"
                    ),
                ),
            ],
            options={
                "verbose_name": "유저별 기도 BGM 재생 상태",
                "verbose_name_plural": "유저별 기도 BGM 재생 상태",
                "db_table": "prayer_bgm_listening_state",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="prayerbgmlisteningstate",
            constraint=models.UniqueConstraint(
                fields=("user", "track"), name="prayer_bgm_listening_state_user_track_unique"
            ),
        ),
    ]
