# Generated by Django 4.2.3 on 2026-01-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bible_reading_log", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="biblereadinglog",
            name="unique_user_bible_reading_log",
        ),
        migrations.RemoveField(
            model_name="biblereadinglog",
            name="book",
        ),
        migrations.RemoveField(
            model_name="biblereadinglog",
            name="chapter",
        ),
        migrations.AddField(
            model_name="biblereadinglog",
            name="count",
            field=models.IntegerField(default=0),
        ),
    ]
