# Generated by Django 4.2.3 on 2026-01-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bible_reading_log", "0002_remove_biblereadinglog_unique_user_bible_reading_log_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="biblereadinglog",
            constraint=models.UniqueConstraint(
                fields=("user", "recognized_date"), name="unique_user_bible_reading_log"
            ),
        ),
    ]
