# Generated by Django 4.2.3 on 2026-01-07 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bible_reading_log", "0003_biblereadinglog_unique_user_bible_reading_log"),
    ]

    operations = [
        migrations.AlterField(
            model_name="biblereadinglog",
            name="count",
            field=models.IntegerField(default=1),
        ),
    ]
