# Generated by Django 4.2.3 on 2025-12-29 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("push_log", "0001_initial"),
        ("sms_log", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                ("recipient", models.CharField(default="", max_length=128, verbose_name="수신자")),
                (
                    "purpose",
                    models.CharField(choices=[("email_authentication", "이메일 인증")], max_length=128, verbose_name="목적"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("R", "대기"), ("S", "성공"), ("F", "실패")], default="R", max_length=1, verbose_name="상태"
                    ),
                ),
                ("fail_reason", models.TextField(blank=True, default="", verbose_name="실패사유")),
            ],
            options={
                "verbose_name": "이메일 로그",
                "verbose_name_plural": "1. 이메일 발송 내역",
                "db_table": "email_log",
            },
        ),
        migrations.CreateModel(
            name="PushLogProxy",
            fields=[],
            options={
                "verbose_name": "3. 푸시알림 발송 내역",
                "verbose_name_plural": "3. 푸시알림 발송 내역",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("push_log.pushlog",),
        ),
        migrations.CreateModel(
            name="SmsLogProxy",
            fields=[],
            options={
                "verbose_name": "2. 문자 발송 내역",
                "verbose_name_plural": "2. 문자 발송 내역",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("sms_log.smslog",),
        ),
    ]
