# Generated by Django 4.2.3 on 2025-12-29 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bible", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BibleVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                ("name", models.CharField(max_length=20, unique=True, verbose_name="버전명")),
                (
                    "bible",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="version_set",
                        to="bible.bible",
                        verbose_name="성경",
                    ),
                ),
            ],
            options={
                "verbose_name": "성경 버전",
                "verbose_name_plural": "성경 버전",
                "db_table": "bible_version",
                "ordering": ["name"],
            },
        ),
    ]
